version: '3.8'
services:
  bank:
    image: vieiraenabled/bank:1.0
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - mysqldb
  mysqldb:
    image: "mysql"
    restart: always
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: bank
      MYSQL_USER: user
      MYSQL_PASSWORD: 1234
      MYSQL_ROOT_PASSWORD: 1234